#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Stage tested CODE_META blocks into a GitHub-ready repository layout."""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import quote

from tools.utils.yaml_utils import dump_data, load_data


def get_items(data: dict[str, Any]) -> list[dict[str, Any]]:
    for key in ("items", "codes", "code_entries", "entries"):
        if isinstance(data.get(key), list):
            return [x for x in data[key] if isinstance(x, dict)]
    nested = data.get("code_manifest")
    if isinstance(nested, dict):
        return get_items(nested)
    return []


def slug(value: Any) -> str:
    text = str(value or "").strip().lower()
    text = text.translate(str.maketrans({"ı":"i","ğ":"g","ü":"u","ş":"s","ö":"o","ç":"c","İ":"i","Ğ":"g","Ü":"u","Ş":"s","Ö":"o","Ç":"c"}))
    text = re.sub(r"[^a-z0-9._-]+", "_", text)
    return re.sub(r"_+", "_", text).strip("_") or "item"


def folder_name(prefix: str, index: int, fallback: Any, prefer_numbered: bool) -> str:
    return f"{prefix}{index:02d}" if prefer_numbered else slug(fallback)


def url_join(*parts: str) -> str:
    cleaned = []
    for i, part in enumerate(parts):
        if not part:
            continue
        cleaned.append(part.rstrip("/") if i == 0 else part.strip("/"))
    return "/".join(cleaned)


def quote_path(path: str) -> str:
    return "/".join(quote(part) for part in path.replace("\\", "/").split("/"))


def load_test_statuses(path: Path | None) -> dict[str, str]:
    if not path or not path.exists():
        return {}
    data = load_data(path)
    return {str(r.get("id")): str(r.get("status", "unknown")) for r in data.get("results", []) if isinstance(r, dict) and r.get("id")}


def read_source_code(path: Path) -> str:
    if path.exists() and path.is_file():
        return path.read_text(encoding="utf-8", errors="replace")
    return ""


def write_code_readme(path: Path, item: dict[str, Any], source_url: str, page_url: str, test_status: str) -> None:
    title = item.get("title") or item.get("title_key") or item.get("file") or item.get("id")
    lines = [
        f"# {title}", "",
        f"- Code ID: `{item.get('id')}`",
        f"- Chapter ID: `{item.get('chapter_id')}`",
        f"- Language: `{item.get('language')}`",
        f"- Test mode: `{item.get('test', 'none')}`",
        f"- Test status: `{test_status}`",
        f"- Source Markdown: `{item.get('source_markdown', '')}`",
        "", "## Links", "",
        f"- Source URL: {source_url}",
        f"- Explanation page: {page_url}",
        "", "Generated by BookFactory GitHub sync.", "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def write_page(path: Path, item: dict[str, Any], repo_code_path: str, source_url: str, page_url: str, test_status: str, code: str) -> None:
    title = str(item.get("title") or item.get("title_key") or item.get("file") or item.get("id"))
    language = str(item.get("language") or "text").lower()
    lines = [
        "---",
        f'title: "{title.replace(chr(34), chr(92)+chr(34))}"',
        f'code_id: "{item.get("id", "")}"',
        f'language: "{language}"',
        f'test_status: "{test_status}"',
        "---", "", f"# {title}", "",
        f"**Kod kimliği:** `{item.get('id')}`  ",
        f"**Bölüm kimliği:** `{item.get('chapter_id')}`  ",
        f"**Dosya:** `{item.get('file')}`  ",
        f"**Dil:** `{language}`  ",
        f"**Test durumu:** `{test_status}`", "",
        "## Bağlantılar", "",
        f"- GitHub kaynak dosyası: {source_url}",
        f"- Açıklama sayfası: {page_url}",
        f"- Repository yolu: `{repo_code_path}`", "",
        "## Kaynak kod", "", f"```{language if language else 'text'}",
        code.rstrip() if code else "// Source code could not be located during sync.",
        "```", "",
        "## Not", "",
        "Bu sayfa BookFactory tarafından CODE_META bloğundan otomatik üretilmiştir.", "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def run_git(command: list[str], cwd: Path) -> int:
    print("$ git " + " ".join(command))
    return subprocess.call(["git", *command], cwd=str(cwd))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Stage tested CODE_META files into a GitHub-ready repository layout.")
    ap.add_argument("--code-manifest", required=True, type=Path)
    ap.add_argument("--test-report", type=Path)
    ap.add_argument("--package-root", type=Path, default=Path.cwd())
    ap.add_argument("--out-dir", type=Path, default=Path("build/github_repo"))
    ap.add_argument("--owner", default="example-owner")
    ap.add_argument("--repo", default="example-book-repo")
    ap.add_argument("--branch", default="main")
    ap.add_argument("--code-root", default="kodlar")
    ap.add_argument("--pages-root", default="docs/kodlar")
    ap.add_argument("--folder-style", choices=["slug", "numbered"], default="numbered")
    ap.add_argument("--include-all", action="store_true")
    ap.add_argument("--require-tests-passed", action="store_true")
    ap.add_argument("--clean", action="store_true")
    ap.add_argument("--enriched-json", type=Path, default=Path("build/code_manifest_github.json"))
    ap.add_argument("--enriched-yaml", type=Path, default=Path("build/code_manifest_github.yaml"))
    ap.add_argument("--report-json", type=Path, default=Path("build/github_sync_report.json"))
    ap.add_argument("--report-md", type=Path, default=Path("build/github_sync_report.md"))
    ap.add_argument("--init-git", action="store_true")
    ap.add_argument("--commit", action="store_true")
    ap.add_argument("--push", action="store_true")
    ap.add_argument("--remote", default="origin")
    ap.add_argument("--commit-message", default="Update BookFactory generated code")
    args = ap.parse_args(argv)

    package_root = args.package_root.resolve()
    code_manifest_path = args.code_manifest if args.code_manifest.is_absolute() else package_root / args.code_manifest
    test_report_path = args.test_report if not args.test_report or args.test_report.is_absolute() else package_root / args.test_report
    out_dir = args.out_dir if args.out_dir.is_absolute() else package_root / args.out_dir
    enriched_json = args.enriched_json if args.enriched_json.is_absolute() else package_root / args.enriched_json
    enriched_yaml = args.enriched_yaml if args.enriched_yaml.is_absolute() else package_root / args.enriched_yaml
    report_json = args.report_json if args.report_json.is_absolute() else package_root / args.report_json
    report_md = args.report_md if args.report_md.is_absolute() else package_root / args.report_md

    items = get_items(load_data(code_manifest_path))
    statuses = load_test_statuses(test_report_path)
    prefer_numbered = args.folder_style == "numbered"
    code_root_path = out_dir / args.code_root
    pages_root_path = out_dir / args.pages_root
    if args.clean:
        shutil.rmtree(code_root_path, ignore_errors=True)
        shutil.rmtree(pages_root_path, ignore_errors=True)
    code_root_path.mkdir(parents=True, exist_ok=True)
    pages_root_path.mkdir(parents=True, exist_ok=True)

    repo_base = f"https://github.com/{args.owner}/{args.repo}/blob/{args.branch}"
    pages_base = f"https://{args.owner}.github.io/{args.repo}"
    chapter_indices: dict[str, int] = {}
    code_indices: dict[str, int] = {}
    staged: list[dict[str, Any]] = []
    skipped: list[dict[str, str]] = []

    for item in items:
        code_id = str(item.get("id", ""))
        chapter_id = str(item.get("chapter_id", "unknown_chapter"))
        if not args.include_all and not bool(item.get("github", False)):
            skipped.append({"id": code_id, "reason": "github_false"})
            continue
        test_status = statuses.get(code_id, "unknown")
        if args.require_tests_passed and test_status != "passed":
            skipped.append({"id": code_id, "reason": f"test_status_{test_status}"})
            continue
        chapter_indices.setdefault(chapter_id, len(chapter_indices) + 1)
        code_indices[chapter_id] = code_indices.get(chapter_id, 0) + 1
        chapter_folder = item.get("chapter_folder") or folder_name("bolum", chapter_indices[chapter_id], chapter_id, prefer_numbered)
        code_folder = item.get("code_folder") or folder_name("kod", code_indices[chapter_id], code_id, prefer_numbered)
        source_code_path = Path(str(item.get("code_path", "")))
        if not source_code_path.is_absolute():
            source_code_path = package_root / source_code_path
        if not source_code_path.exists():
            skipped.append({"id": code_id, "reason": f"missing_code_path_{source_code_path}"})
            continue
        target_dir = code_root_path / str(chapter_folder) / str(code_folder)
        target_dir.mkdir(parents=True, exist_ok=True)
        target_file = target_dir / str(item.get("file") or source_code_path.name)
        shutil.copy2(source_code_path, target_file)
        code_text = read_source_code(source_code_path)
        repo_code_path = str(target_file.relative_to(out_dir)).replace(os.sep, "/")
        source_url = url_join(repo_base, quote_path(repo_code_path))
        page_dir = pages_root_path / str(chapter_folder) / str(code_folder)
        page_file = page_dir / "index.md"
        site_path = str(page_dir.relative_to(out_dir / "docs") if str(args.pages_root).startswith("docs") else page_dir.relative_to(out_dir)).replace(os.sep, "/")
        page_url = url_join(pages_base, quote_path(site_path), "")
        write_code_readme(target_dir / "README.md", item, source_url, page_url, test_status)
        write_page(page_file, item, repo_code_path, source_url, page_url, test_status, code_text)
        enriched = dict(item)
        enriched.update({
            "github": True,
            "github_status": "staged",
            "test_status": test_status,
            "repo_code_path": repo_code_path,
            "repo_page_path": str(page_file.relative_to(out_dir)).replace(os.sep, "/"),
            "github_source_url": source_url,
            "github_page_url": page_url,
            "chapter_folder": str(chapter_folder),
            "code_folder": str(code_folder),
        })
        staged.append(enriched)

    index_lines = [
        "# BookFactory Generated Code Index", "",
        f"Generated at: `{datetime.now(timezone.utc).isoformat()}`", "",
        "| Chapter | Code | File | Test | Source | Page |", "|---|---|---|---|---|---|",
    ]
    for item in staged:
        index_lines.append(f"| `{item.get('chapter_folder')}` | `{item.get('code_folder')}` | `{item.get('file')}` | `{item.get('test_status')}` | [source]({item.get('github_source_url')}) | [page]({item.get('github_page_url')}) |")
    (out_dir / args.code_root / "README.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    (out_dir / "docs" / "index.md").parent.mkdir(parents=True, exist_ok=True)
    (out_dir / "docs" / "index.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")

    enriched_manifest = {"schema_version": "1.2", "generated_at": datetime.now(timezone.utc).isoformat(), "source_code_manifest": str(code_manifest_path), "repository": {"owner": args.owner, "repo": args.repo, "branch": args.branch}, "items": staged}
    dump_data(enriched_manifest, enriched_json, enriched_yaml)
    report = {"schema_version": "1.1", "generated_at": datetime.now(timezone.utc).isoformat(), "out_dir": str(out_dir), "staged_count": len(staged), "skipped_count": len(skipped), "staged": [{"id": i.get("id"), "repo_code_path": i.get("repo_code_path"), "github_source_url": i.get("github_source_url"), "github_page_url": i.get("github_page_url")} for i in staged], "skipped": skipped}
    report_json.parent.mkdir(parents=True, exist_ok=True)
    report_json.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    report_md.parent.mkdir(parents=True, exist_ok=True)
    report_md.write_text("# BookFactory GitHub Sync Report\n\n" f"- Staged: {len(staged)}\n" f"- Skipped: {len(skipped)}\n" f"- Output directory: `{out_dir}`\n" f"- Enriched manifest: `{enriched_json}`\n\n", encoding="utf-8")

    if args.init_git and not (out_dir / ".git").exists():
        if run_git(["init"], out_dir) != 0:
            return 3
        run_git(["checkout", "-B", args.branch], out_dir)
    if args.commit:
        if not (out_dir / ".git").exists():
            print("[ERROR] --commit requires --init-git or an existing git repository.", file=sys.stderr)
            return 4
        if run_git(["add", "."], out_dir) != 0:
            return 5
        if run_git(["commit", "-m", args.commit_message], out_dir) != 0:
            print("[WARN] git commit returned non-zero. This may mean there were no changes.")
    if args.push:
        if not (out_dir / ".git").exists():
            print("[ERROR] --push requires an existing git repository.", file=sys.stderr)
            return 6
        if run_git(["push", args.remote, args.branch], out_dir) != 0:
            return 7
    print(f"[OK] Staged code entries: {len(staged)}")
    print(f"[OK] Skipped code entries: {len(skipped)}")
    print(f"[OK] GitHub-ready repo: {out_dir}")
    print(f"[OK] Enriched manifest: {enriched_json}")
    return 0 if staged or not args.require_tests_passed else 2


if __name__ == "__main__":
    raise SystemExit(main())
